### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by esatterwhite** [edwardchoh/zmqbus-node#8]
There hasn't been much activity here in years, is this dead? I doesn't work on recent versions of node.
@edwardchoh  I'm insterested in working on this, if you no longer want to / have time.

**Comment by edwardchoh** [comment]
I'll make sure pull requests are merged quickly.

Any idea what else would you be adding to this module?

**Comment by esatterwhite** [comment]
Well with Node 6 about to become LTS & 99%+ es6 support, I think it is time to get rid of the coffee script.
It looks like the [pgm node stuff isn't really supported](https://github.com/edwardchoh/zmqbus-node/blob/4010daf7b57030dde759d9be9729dfcdefaf22eb/src/index.coffee#L25) (?). The code could just be remove all together.

There are also some changes to the dgram module in v6 and libuv that should be chaged. Mainly multicast address reuse is handled.

I'd like to add some simple [debug](https://www.npmjs.com/package/debug) / logging as well. would be really helpful in tracking down bugs.

Some better documentation one the code base would be nice for people looking to build on what is already there. 

I don't think there is much functionality to be added, just _keepin' up with the jones'_

**Comment by edwardchoh** [comment]
Ok, sounds good. Although it doesn't seem to be worth the effort since this module isn't very popular. Last month it had 56 downloads in npm.

Anyway, I'll gladly merge in your changes. Another way to go is to map the npm module to your fork (if that's possible at all). Let me know what will work for you.

**Comment by esatterwhite** [comment]
you could add me as a collaborator on the npm package  rather mapping forks.

**Comment by edwardchoh** [comment]
Done, you're added.
